"""Reset migration history

Revision ID: 1fa70d3aa391
Revises: 
Create Date: 2024-10-04 22:15:17.158645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa70d3aa391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('introduction', sa.TEXT(), nullable=False),
    sa.Column('execution_title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('execution_body', sa.TEXT(), nullable=False),
    sa.Column('problems_title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('problems_body', sa.TEXT(), nullable=False),
    sa.Column('solutions_title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('solutions_body', sa.TEXT(), nullable=False),
    sa.Column('total_projects', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
