"""projects model

Revision ID: f2fcbabda1ba
Revises: a01370ba2359
Create Date: 2024-10-12 00:00:36.543578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2fcbabda1ba'
down_revision = 'a01370ba2359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image2_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image2_url')
        batch_op.drop_column('image1_url')

    # ### end Alembic commands ###
